// this is not going to be a primitive object its going to be a real model that we are going to interact with
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-f372c04de44640fbb6a4f9e4e5845c78
Title: Fox
*/
import * as THREE from "three"; // add this at the top

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "../assets/3d/fox.glb";

const Fox = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // if (!actions || !currentAnimation) return;

    // Step 1: Fade out whatever animation is currently playing.
    // Step 2: Pick the animation you want (currentAnimation).
    // Step 3: Reset it, fade it in smoothly, and start playing it.
    // Step 4: Make it loop and optionally slow it down.  action.setLoop(THREE.LoopRepeat);
    // Smoothly fade out all current animations
    Object.values(actions).forEach((action) => {
      action.fadeOut(0.2);
    }); //If the fox is walking and you want it to do a hit, you don’t want the walk animation and the hit animation to play at the same time, or it will look weird.

    // So stop() makes sure everything else stops first, and then you can safely start the animation you want.

    // ✅ Simple rule: stop all animations → play the one you want.

    const action = actions[currentAnimation];
    if (action) {
      action.reset().fadeIn(0.2).play();
      action.clampWhenFinished = true; //When the animation finishes, it stays in its last frame instead of snapping back to the first frame.
      action.timeScale = 0.8; // slightly slower for visibility
      action.setLoop(THREE.LoopRepeat);
    }
  }, [currentAnimation, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_9.skeleton}
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_10.skeleton}
        />
        <skinnedMesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_11.skeleton}
        />
      </group>
    </group>
  );
};

export default Fox;
